version: '3.9'

x-logging: &logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "1"

services:
  nginx:
    image: "nginx:1.23"
    ports:
      - "9889:80"
    volumes:
      - ./www:/usr/share/nginx/html
    logging: *logging