version: '3.9'

x-logging: &logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "1"

services:
  nginx:
    image: "nginx:1.23"
    ports:
      - "80:80"
    volumes:
      - /var/www:/var/www
    logging: *logging